### ISSUE TITLE
identityserver example could be expanded

### ISSUE THREAD

**Issue by ryan-morris** [ChrisKlug/asp.net-core-2.0-auth-demo#2]
I thought your [talk](https://youtu.be/-50ntzz18XU) was great but I'm still left with some questions on the IdentityServer sample. I know configuring IdentityServer was not the focus, but in your other samples you have a `UserService`, you could expand your sample to show how to implement existing services we may have.  99% of the guides for IdentityServer rely on either `AddTestUsers` or the ASPNET Identity with EntityFramework, what I liked so much about your other projects was the fact it was built up from scratch showing how you could actually implement the under the hood features without imposing constraints like EF.

Thanks so much for contributing content to the community!

**Comment by ChrisKlug** [comment]
Hi Ryan!
It's great to hear that you enjoyed it! I means a lot!
As for your request to update the example with a custom implementation of the user repository, I would love to say yes to that. Unfortunately I have a bit too much on my plate right now. I will keep it in mind though, if I do end up having some down time in the near future!
Cheers,
Chris

**Comment by ryan-morris** [comment]
Yes, no problem. Just a suggestion in case you have to remake it for any aspnet changes in the future
